sudo: false
language: python
python: 2.7

install:
  - make bootstrap

script:
  - make test

branches:
  only:
    - master

notifications:
  email: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Nx+LmWOfmC0fKJGUJBhw9AGDzrt02qncaDOX7Vzpz7EIKX/rEgPtnDE8mijIBmnBwXj5vGRw5xq4tmZ6GLKH5HkiwTngtVJuV/n0jHgkVp2gfNnKpTJcLie9v2HjgPX6HSueU+pGZLr8X+65OuOEaSBguHLyOJ5YDwVxU3laRb5Sf/Lv6xtJP5vhbMtYRh458MPvy94qcVAc3w7qxoUneAVISEbH6ocgLqkki4LZdtmL4A0Gu9mhnlPCag+Tt2u2fNenU6267F1QgXAtT2cQRJZxbXR436aAlASndOzUoKonVZdBbt9dUFZyrZTpMPhPn8oAqPfi1eVfX9c3iDgz7t76umXYu9juC27vj/45+ForwdExVcFqcWdQVrfTf22kD88xlKssCtTvuW+IfAsIifxthBBSBKJY5LnZbmzhScq2GFE4cNLHRHxnQ+5K0maLFVIwafBQDxKkgBGRgNmUlGGSz0CFRlBUc4Y3E6TFtAudbDRklogxs3C7fW0zD+CE2D+vfAKQTPtYkxfhPJDeIqcSJY1+3gJ47+XaK82kqYfd4shC5IntUzerEoxMx6BUYaGYhpT4B7MuJBVs0KbExFAQ+RgMacjZWOBUoqdewfWFmv0lE9xbWhCsnUPnc4z18MyxXRHVUtdqLiHkD7SWYYfZK89wGmaecan0u699LVo="

addons:
  coverity_scan:
    project:
      name: "cjlm007/tornado_skeleton"
      description: "tornado skeleton"
    build_command_prepend: "make bootstrap"
    build_command: "make test"
    branch_pattern: coverity_scan
