sudo: false
language: python
python: 2.7

install:
  - make bootstrap

script:
  - make test
  - make report

branches:
  only:
    - master

notifications:
  email: false

addons:
  code_climate:
    repo_token: f49e0e055395186fb1eb773362e86306d8a043f4b383e8d4bec85780c2a2f61f
