server:
  port: 18888
  
extends:
  - "./config/base.yaml"
deep_extend: true
database:
  module: psycopg2
  read:
    -
      dbname: bootcamp_test
      user: bootcamp_test
      port: 5432
  write:
    -
      dbname: bootcamp_test
      user: bootcamp_test
      port: 5432
